# Site settings
title: Jie Yang
academic_email: j.yang-3@tudelft.nl

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://ys1998.github.io" # the base hostname & protocol for your site

twitter_username: yangjiera
linkedin_username: yangjiera
google_scholar: DAlsOOEAAAAJ
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

location: "3W760 (3rd floor, West, Room 760) <br /> 
Van Mourik Broekmanweg 6 <br />
2628 XE Delft, 
The Netherlands"

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax